name: AmazinUtilities
version: '${project.version}'
main: com.amazindev.amazinutilities.AmazinUtilities
api-version: 1.17
authors: [ AmazinAmazon, Enrimangamer ]
description: A simple alternative to EssentialsX
website: amazindev.com
commands:
  gma:
    description: Go in adventure mode
    usage: /<command> <player>
  gmc:
    description: Go in creative mode
    usage: /<command> <player>
  gmsp:
    description: Go in spectator mode
    usage: /<command> <player>
  gms:
    description: Go in survival mode
    usage: /<command> <player>
  announcement:
    description: Make an announcement in chat.
    usage: </command> <args>
    aliases:
      - announce
      - ann
  tphere:
    description: Tp someone to your location
    usage: /<command> <player>