name: AmazinUtilities
version: '${project.version}'
main: com.amazindev.amazinutilities.AmazinUtilities
api-version: 1.17
authors: [ AmazinAmazon, Enrimangamer ]
description: A simple alternative to EssentialsX
website: amazindev.com
commands:
  gma:
    description: Go in adventure mode
    usage: /<command> [player]
  gmc:
    description: Go in creative mode
    usage: /<command> [player]
  gmsp:
    description: Go in spectator mode
    usage: /<command> [player]
  gms:
    description: Go in survival mode
    usage: /<command> [player]
  announcement:
    description: Make an announcement in chat.
    usage: /<command> <args>
    aliases:
      - announce
      - ann
      - broadcast
  tphere:
    description: Tp someone to your location
    usage: /<command> <player>
  afk:
    description: Go afk
    usage: /<command>
  tp2p:
    description: Tp directly to someone
    usage: /<command> <player>
    aliases:
      - tp2player
  day:
    description: Set the time in your world to day
    usage: /<command>
  night:
    description: Set the time in your world to night
    usage: /<command>
  setspawn:
    description: Sets the spawn of the currect world
    usage: /<command>
  spawn:
    description: Teleport to the world spawn
    usage: /<command>
  ybar:
    description: Shows y coord in a bossbar
    usage: /<command>
  shutdown:
    description: Shutdown the server with warnings
    usage: /<command>
    aliases:
      - restart
  chatcolor:
    description: Change the color of all your messages in chat
    usage: /<command> <color> [style]
  tpall:
    description: Tp all the players to your location
    usage: /<command>
  kickall:
    description: Kick all the players in the server
    usage: /<command> <reason>
  ping:
    description: See your ping
    usage: /<command>
  fly:
    description: Make yourself fly
    usage: /<command>
  seetime:
    description: See the time in your world
    usage: /<command>
  amazinutilities:
    description: Info on the plugin
    usage: /<command> [reload]
  rules:
    description: Read the server rules
    usage: /<command>
  whois:
    description: Know everything about someone
    usage: /<command> <player>